require:
  - rubocop-rspec
  - rubocop/rspec/focused

AllCops:
  TargetRubyVersion: 2.7.2

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 10

RSpec/Focused:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'vamoos.gemspec'
RSpec/FilePath:
  Exclude:
    - 'spec/lib/core_ext/**/*'
RSpec/NestedGroups:
  Exclude:
    - 'spec/**/*'
